// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaE76XSUdITIIxZO_3NHA4hArY9nzUpgs',
    appId: '1:901764302831:web:da2d75f9bb813ee8a8d81a',
    messagingSenderId: '901764302831',
    projectId: 'to-do-list-97fa7',
    authDomain: 'to-do-list-97fa7.firebaseapp.com',
    storageBucket: 'to-do-list-97fa7.firebasestorage.app',
    measurementId: 'G-TDF2EKEKMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVnFEvNbqlgKUUNSywUb2mOyWp0xVhCqo',
    appId: '1:901764302831:android:ec14882954bc9ce7a8d81a',
    messagingSenderId: '901764302831',
    projectId: 'to-do-list-97fa7',
    storageBucket: 'to-do-list-97fa7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1lO04GFoORgBkUDM54U0VK-0YCNm8UcQ',
    appId: '1:901764302831:ios:a5ed99e7f9f8e895a8d81a',
    messagingSenderId: '901764302831',
    projectId: 'to-do-list-97fa7',
    storageBucket: 'to-do-list-97fa7.firebasestorage.app',
    iosBundleId: 'com.example.toDo',
  );
}
